---
docker_deploy_image: hello-world:latest
docker_deploy_container_name: hello_world

docker_deploy_detach: true
docker_deploy_restart_policy: unless-stopped
docker_deploy_networks: []

docker_deploy_ports: []
docker_deploy_env: {}

docker_deploy_host_dirs: []
docker_deploy_mounts: []

docker_deploy_extract_static: false
docker_deploy_static_src_path: "/app/frontend-dist"
docker_deploy_static_dest: "/opt/bulletins/static"

docker_deploy_track_releases: true
docker_deploy_release_dir: /opt/bulletins/release

docker_deploy_registry: ""
docker_deploy_registry_username: ""
docker_deploy_registry_password: ""
